import { MigrationInterface, QueryRunner } from "typeorm";

export class Auto1767431336380 implements MigrationInterface {
    name = 'Auto1767431336380'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."notifications_channel_enum" AS ENUM('email', 'sms', 'in_app')`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_type_enum" AS ENUM('trip_reminder_24h', 'trip_reminder_3h', 'trip_live_update', 'booking_confirmation', 'booking_incomplete')`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_status_enum" AS ENUM('pending', 'sent', 'failed', 'read')`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" character varying NOT NULL, "channel" "public"."notifications_channel_enum" NOT NULL, "type" "public"."notifications_type_enum" NOT NULL, "status" "public"."notifications_status_enum" NOT NULL DEFAULT 'pending', "payload" jsonb, "sentAt" TIMESTAMP WITH TIME ZONE, "readAt" TIMESTAMP WITH TIME ZONE, "bookingId" uuid, CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_692a909ee0fa9383e7859f9b40" ON "notifications" ("userId") `);
        await queryRunner.query(`CREATE TABLE "passenger_details" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "bookingId" uuid NOT NULL, "fullName" character varying NOT NULL, "documentId" character varying NOT NULL, "seatCode" character varying NOT NULL, "checkedInAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_06422dddff22d9af8cf874c6d2e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_919ee9cc0acf9c0e2066eb51bb" ON "passenger_details" ("bookingId") `);
        await queryRunner.query(`CREATE TYPE "public"."payments_status_enum" AS ENUM('PENDING', 'PAID', 'FAILED', 'EXPIRED')`);
        await queryRunner.query(`CREATE TABLE "payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "orderCode" integer NOT NULL, "paymentLinkId" character varying, "provider" character varying NOT NULL, "status" "public"."payments_status_enum" NOT NULL DEFAULT 'PENDING', "amount" numeric(10,2) NOT NULL, "currency" character varying NOT NULL DEFAULT 'VND', "transactionRef" character varying, "paidAt" TIMESTAMP WITH TIME ZONE, "bookingId" uuid NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_197ab7af18c93fbb0c9b28b4a59" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1ead3dc5d71db0ea822706e389" ON "payments" ("bookingId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_a28f9de43c3c1299c065e64018" ON "payments" ("orderCode") `);
        await queryRunner.query(`CREATE TABLE "seats" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "busId" uuid NOT NULL, "seatCode" character varying NOT NULL, "seatType" character varying NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "deletedAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_3fbc74bb4638600c506dcb777a7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_df91783ed26705224099ed0961" ON "seats" ("busId") `);
        await queryRunner.query(`CREATE TABLE "buses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "operatorId" uuid NOT NULL, "plateNumber" character varying NOT NULL, "model" character varying NOT NULL, "busType" character varying, "seatCapacity" integer NOT NULL, "amenitiesJson" text, "isActive" boolean NOT NULL DEFAULT true, "deletedAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_ddebc0eeba64a019ae072975947" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2a269d108c3a161a30982d8273" ON "buses" ("operatorId") `);
        await queryRunner.query(`CREATE TABLE "operators" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "contactEmail" character varying NOT NULL, "contactPhone" character varying NOT NULL, "status" character varying NOT NULL, "approvedAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_3d02b3692836893720335a79d1b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "route_points" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "routeId" uuid NOT NULL, "type" character varying NOT NULL, "name" character varying NOT NULL, "address" character varying NOT NULL, "latitude" numeric(10,7), "longitude" numeric(10,7), "orderIndex" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_9684d129d71ff38906e7cb08c68" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a2eab28234f80f4a7962495d5b" ON "route_points" ("routeId") `);
        await queryRunner.query(`CREATE TABLE "routes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "operatorId" uuid, "origin" character varying NOT NULL, "destination" character varying NOT NULL, "distanceKm" integer NOT NULL, "estimatedMinutes" integer NOT NULL, "notes" character varying, "isActive" boolean NOT NULL DEFAULT true, "deletedAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_76100511cdfa1d013c859f01d8b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c300d7904921af7cab0d1aef27" ON "routes" ("operatorId") `);
        await queryRunner.query(`CREATE TABLE "feedbacks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tripId" uuid NOT NULL, "userId" uuid NOT NULL, "rating" integer NOT NULL, "comment" text, "submittedAt" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "PK_79affc530fdd838a9f1e0cc30be" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_aee87b31c34a194aaeddeced80" ON "feedbacks" ("tripId") `);
        await queryRunner.query(`CREATE INDEX "IDX_e9b6450d76be18b05b5f09d577" ON "feedbacks" ("userId") `);
        await queryRunner.query(`CREATE TABLE "trips" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "routeId" uuid NOT NULL, "busId" uuid NOT NULL, "departureTime" TIMESTAMP WITH TIME ZONE NOT NULL, "arrivalTime" TIMESTAMP WITH TIME ZONE NOT NULL, "basePrice" numeric(10,2) NOT NULL, "status" character varying NOT NULL, CONSTRAINT "PK_f71c231dee9c05a9522f9e840f5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3fcad6442389eeb7aea5f1f25a" ON "trips" ("routeId") `);
        await queryRunner.query(`CREATE INDEX "IDX_5cb200e0bc5828053dd3d60cfd" ON "trips" ("busId") `);
        await queryRunner.query(`CREATE TABLE "seat_statuses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tripId" uuid NOT NULL, "seatId" uuid NOT NULL, "state" character varying NOT NULL, "bookingId" uuid, "lockedUntil" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_e5767a6ad3420996f7ad8868ea3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_aec5d7800cc25321e9b1338445" ON "seat_statuses" ("tripId") `);
        await queryRunner.query(`CREATE INDEX "IDX_9b5910eeef4f62892e5a1e1001" ON "seat_statuses" ("seatId") `);
        await queryRunner.query(`CREATE TABLE "bookings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid, "tripId" uuid NOT NULL, "status" character varying NOT NULL, "totalAmount" numeric(10,2) NOT NULL, "bookedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "reminder24hSentAt" TIMESTAMP WITH TIME ZONE, "reminder3hSentAt" TIMESTAMP WITH TIME ZONE, "name" character varying, "email" character varying, "phone" character varying, "pickupPointId" uuid, "dropoffPointId" uuid, "ticketToken" character varying, "ticketTokenIssuedAt" TIMESTAMP WITH TIME ZONE, "checkedInAt" TIMESTAMP WITH TIME ZONE, "bookingReference" character varying NOT NULL, CONSTRAINT "PK_bee6805982cc1e248e94ce94957" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_38a69a58a323647f2e75eb994d" ON "bookings" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_e33f0b046a54956d011b3d377e" ON "bookings" ("tripId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_efae15c3deed139b3a0ce03f69" ON "bookings" ("bookingReference") `);
        await queryRunner.query(`CREATE TABLE "payment_methods" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "provider" character varying NOT NULL, "token" character varying NOT NULL, "isDefault" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_34f9b8c6dfb4ac3559f7e2820d1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_580f1dbf7bceb9c2cde8baf7ff" ON "payment_methods" ("userId") `);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "firstName" character varying(100) NOT NULL, "lastName" character varying(100) NOT NULL, "email" character varying(100) NOT NULL, "phone" character varying(15), "password" character varying(100), "googleId" character varying(100), "avatarUrl" character varying(255) DEFAULT '', "avatar_media_id" uuid, "username" character varying(50), "bio" text, "role" character varying(20) NOT NULL DEFAULT 'USER', "isVerified" boolean NOT NULL DEFAULT false, "isActive" boolean NOT NULL DEFAULT true, "hasSetPassword" boolean NOT NULL DEFAULT false, "verificationToken" character varying(200), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "UQ_a000cca60bcf04454e727699490" UNIQUE ("phone"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "notification_preferences" ("userId" uuid NOT NULL, "emailRemindersEnabled" boolean NOT NULL DEFAULT true, "smsRemindersEnabled" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_b70c44e8b00757584a393225593" PRIMARY KEY ("userId"))`);
        await queryRunner.query(`CREATE TYPE "public"."media_domain_enum" AS ENUM('bus', 'route', 'trip', 'user')`);
        await queryRunner.query(`CREATE TYPE "public"."media_type_enum" AS ENUM('image', 'avatar', 'bus_photo')`);
        await queryRunner.query(`CREATE TABLE "media" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "domain" "public"."media_domain_enum" NOT NULL, "domain_id" uuid NOT NULL, "type" "public"."media_type_enum" NOT NULL, "key" character varying(500), "mime" character varying(150), "size" bigint DEFAULT '0', "url" character varying(500) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_f4e0fcac36e050de337b670d8bd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c6d1d553868e9375a3b10864fd" ON "media" ("domain", "domain_id") `);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_ac07a6d4dd6fdb761c6df54760e" FOREIGN KEY ("bookingId") REFERENCES "bookings"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "passenger_details" ADD CONSTRAINT "FK_919ee9cc0acf9c0e2066eb51bbf" FOREIGN KEY ("bookingId") REFERENCES "bookings"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_1ead3dc5d71db0ea822706e389d" FOREIGN KEY ("bookingId") REFERENCES "bookings"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "seats" ADD CONSTRAINT "FK_df91783ed26705224099ed09613" FOREIGN KEY ("busId") REFERENCES "buses"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "buses" ADD CONSTRAINT "FK_2a269d108c3a161a30982d82738" FOREIGN KEY ("operatorId") REFERENCES "operators"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "route_points" ADD CONSTRAINT "FK_a2eab28234f80f4a7962495d5b6" FOREIGN KEY ("routeId") REFERENCES "routes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "routes" ADD CONSTRAINT "FK_c300d7904921af7cab0d1aef27b" FOREIGN KEY ("operatorId") REFERENCES "operators"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "feedbacks" ADD CONSTRAINT "FK_aee87b31c34a194aaeddeced809" FOREIGN KEY ("tripId") REFERENCES "trips"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "feedbacks" ADD CONSTRAINT "FK_e9b6450d76be18b05b5f09d577b" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trips" ADD CONSTRAINT "FK_3fcad6442389eeb7aea5f1f25a8" FOREIGN KEY ("routeId") REFERENCES "routes"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trips" ADD CONSTRAINT "FK_5cb200e0bc5828053dd3d60cfd8" FOREIGN KEY ("busId") REFERENCES "buses"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "seat_statuses" ADD CONSTRAINT "FK_aec5d7800cc25321e9b13384459" FOREIGN KEY ("tripId") REFERENCES "trips"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "seat_statuses" ADD CONSTRAINT "FK_9b5910eeef4f62892e5a1e10014" FOREIGN KEY ("seatId") REFERENCES "seats"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "seat_statuses" ADD CONSTRAINT "FK_33729bd3dc00e6c228abbcd1d82" FOREIGN KEY ("bookingId") REFERENCES "bookings"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_38a69a58a323647f2e75eb994de" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_e33f0b046a54956d011b3d377ef" FOREIGN KEY ("tripId") REFERENCES "trips"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_methods" ADD CONSTRAINT "FK_580f1dbf7bceb9c2cde8baf7ff4" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification_preferences" ADD CONSTRAINT "FK_b70c44e8b00757584a393225593" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "notification_preferences" DROP CONSTRAINT "FK_b70c44e8b00757584a393225593"`);
        await queryRunner.query(`ALTER TABLE "payment_methods" DROP CONSTRAINT "FK_580f1dbf7bceb9c2cde8baf7ff4"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_e33f0b046a54956d011b3d377ef"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_38a69a58a323647f2e75eb994de"`);
        await queryRunner.query(`ALTER TABLE "seat_statuses" DROP CONSTRAINT "FK_33729bd3dc00e6c228abbcd1d82"`);
        await queryRunner.query(`ALTER TABLE "seat_statuses" DROP CONSTRAINT "FK_9b5910eeef4f62892e5a1e10014"`);
        await queryRunner.query(`ALTER TABLE "seat_statuses" DROP CONSTRAINT "FK_aec5d7800cc25321e9b13384459"`);
        await queryRunner.query(`ALTER TABLE "trips" DROP CONSTRAINT "FK_5cb200e0bc5828053dd3d60cfd8"`);
        await queryRunner.query(`ALTER TABLE "trips" DROP CONSTRAINT "FK_3fcad6442389eeb7aea5f1f25a8"`);
        await queryRunner.query(`ALTER TABLE "feedbacks" DROP CONSTRAINT "FK_e9b6450d76be18b05b5f09d577b"`);
        await queryRunner.query(`ALTER TABLE "feedbacks" DROP CONSTRAINT "FK_aee87b31c34a194aaeddeced809"`);
        await queryRunner.query(`ALTER TABLE "routes" DROP CONSTRAINT "FK_c300d7904921af7cab0d1aef27b"`);
        await queryRunner.query(`ALTER TABLE "route_points" DROP CONSTRAINT "FK_a2eab28234f80f4a7962495d5b6"`);
        await queryRunner.query(`ALTER TABLE "buses" DROP CONSTRAINT "FK_2a269d108c3a161a30982d82738"`);
        await queryRunner.query(`ALTER TABLE "seats" DROP CONSTRAINT "FK_df91783ed26705224099ed09613"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_1ead3dc5d71db0ea822706e389d"`);
        await queryRunner.query(`ALTER TABLE "passenger_details" DROP CONSTRAINT "FK_919ee9cc0acf9c0e2066eb51bbf"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_ac07a6d4dd6fdb761c6df54760e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c6d1d553868e9375a3b10864fd"`);
        await queryRunner.query(`DROP TABLE "media"`);
        await queryRunner.query(`DROP TYPE "public"."media_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."media_domain_enum"`);
        await queryRunner.query(`DROP TABLE "notification_preferences"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_580f1dbf7bceb9c2cde8baf7ff"`);
        await queryRunner.query(`DROP TABLE "payment_methods"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_efae15c3deed139b3a0ce03f69"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e33f0b046a54956d011b3d377e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_38a69a58a323647f2e75eb994d"`);
        await queryRunner.query(`DROP TABLE "bookings"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9b5910eeef4f62892e5a1e1001"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_aec5d7800cc25321e9b1338445"`);
        await queryRunner.query(`DROP TABLE "seat_statuses"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5cb200e0bc5828053dd3d60cfd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3fcad6442389eeb7aea5f1f25a"`);
        await queryRunner.query(`DROP TABLE "trips"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e9b6450d76be18b05b5f09d577"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_aee87b31c34a194aaeddeced80"`);
        await queryRunner.query(`DROP TABLE "feedbacks"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c300d7904921af7cab0d1aef27"`);
        await queryRunner.query(`DROP TABLE "routes"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a2eab28234f80f4a7962495d5b"`);
        await queryRunner.query(`DROP TABLE "route_points"`);
        await queryRunner.query(`DROP TABLE "operators"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2a269d108c3a161a30982d8273"`);
        await queryRunner.query(`DROP TABLE "buses"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_df91783ed26705224099ed0961"`);
        await queryRunner.query(`DROP TABLE "seats"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a28f9de43c3c1299c065e64018"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1ead3dc5d71db0ea822706e389"`);
        await queryRunner.query(`DROP TABLE "payments"`);
        await queryRunner.query(`DROP TYPE "public"."payments_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_919ee9cc0acf9c0e2066eb51bb"`);
        await queryRunner.query(`DROP TABLE "passenger_details"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_692a909ee0fa9383e7859f9b40"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_channel_enum"`);
    }

}
